-- 1. Create a table to store the fingerprint data
CREATE TABLE fingerprint_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint BLOB
);

--  2. Create a sequence to generate the primary key
CREATE SEQUENCE fingerprint_data_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

--  3. Create a trigger to populate the primary key
CREATE OR REPLACE TRIGGER fingerprint_data_trigger
    BEFORE INSERT ON fingerprint_data
    FOR EACH ROW
BEGIN
    SELECT fingerprint_data_seq.NEXTVAL
    INTO :new.id
    FROM dual;
END;